global using ECommerce.Core.Entities;
global using ECommerce.Core.Interfaces.Repository;
global using ECommerce.Core.Interfaces.Services;
global using ECommerce.Core.Responses;
global using AutoMapper;
global using ECommerce.Core.DTOS;
global using ECommerce.Core.CustomEntities;
global using ECommerce.Core.Interfaces.Specifications;
global using System.Net;